### ISSUE TITLE
measure won't work with jest

### ISSUE THREAD

**Issue by BraunreutherA** [maraisr/rian#2]
### Describe the bug

When using measure in a jest test, a error appears that says `.has` is called on undefined. The only call of .has is done on the WeakMap in the index.ts. 
The utils import this, ADD_PROMISES and the index imports measureFn from the utils -> we could run in a circular dependency here, which jest doesn't like.

### To reproduce

Use `measure` in a function which gets then executed in a jest test.

### Expected behavior

`measure` should not break jest tests

### Validations

- [X] Follow our [Code of Conduct](https://github.com/maraisr/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/maraisr/.github/blob/main/CONTRIBUTING.md).
- [X] Is there already an issue for this?

**Comment by theKashey** [comment]
`index` -> `utils` -> `index`
And eslint cannot catch it due to package self-reference used.

This is a good example of the difference between web bundler and node - latest will return an empty object if you import a file you already have in the "require stack".

**Comment by maraisr** [comment]
hey 👋🏻  thanks for the issue. And oh gosh! Will resolve asap.

**Comment by maraisr** [comment]
I've raised a PR to address the issue 👉 #3 let me know what you think. It should resolve the issue, and probably even better this way.

If no comments, ill merge and release 🚀

**Comment by maraisr** [comment]
@BraunreutherA thanks for this issue, and sorry about the delayed release. Please have a try at 0.2.3 🚀
